services:
  vintage-culture:
    container_name: vintage-culture
    image: vintage-culture:latest
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
